name: PR Workflow
on:
  pull_request:
    branches:
      - main
jobs:
  check:
    runs-on: ubuntu-latest
    permissions:
      checks: write
    steps:
      - name: checkout code repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: setup node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Cache .pnpm-store
        uses: actions/cache@v1
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-node${{ matrix.node-version }}-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: Install pnpm
        run: |
          npm i -g pnpm
          pnpm set verify-store-integrity false

      - name: pnpm install
        run: |
          pnpm install --frozen-lockfile

      - name: Build packages
        run: pnpm build

      - name: Lint types and code
        run: pnpm lint

      - name: Run tests
        run: pnpm test

      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.9

      - name: Run e2e tests
        run: pnpm e2e

      - name: Create a check run
        uses: actions/github-script@v6
        env:
          parameter_url: '${{ github.event.workflow_run.html_url }}'
        with:
          debug: ${{ secrets.ACTIONS_STEP_DEBUG || false }}
          script: |
            // any JavaScript code can go here, you can use Node JS APIs too.
            // Docs: https://docs.github.com/en/rest/checks/runs#create-a-check-run
            // Rest: https://octokit.github.io/rest.js/v18#checks-create
            await github.rest.checks.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              head_sha: context.sha,
              name: "my-check-name",
              status: "completed",
              // Careful, code injection can happen.
              conclusion: "${{ job.status }}",
              // This is safe, not string interpolation.
              output: {
                title: "my check title",
                summary: "my *check* summary",
                text: "my text",
              },
            });
